# Generated by Django 5.2.4 on 2025-08-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this menu item', null=True, upload_to='menu_images/'),
        ),
    ]
